apiVersion: "v1"
kind: "Service"
metadata:
  name: "orders-service"
  namespace: "default"
  labels:
    app: "orders"
spec:
  ports:
  - protocol: "TCP"
    port: 3001
    targetPort: 3001
  selector:
    app: "orders"
  type: "LoadBalancer"
