version: '2.0'
services:
    user:
        container_name: user
        restart: always
        build: './user'
        ports:
            - '3000:3000'
        links:
            - mongodb

    orders:
        container_name: orders
        restart: always
        build: './orders'
        ports:
            - '3001:3001'

    aggreator:
        container_name: aggregator
        restart: always
        build: './aggregator'
        ports:
            - '3002:3002'

    mongodb:
        container_name: mongo
        image: mongo
        ports:
            - '27017:27017'