apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "user"
  namespace: "default"
  labels:
    app: "user"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "user"
  template:
    metadata:
      labels:
        app: "user"
    spec:
      containers:
      - name: "user-sha256-1"
        image: "gcr.io/microservices-277115/user:v2.0"
        ports:
        - containerPort: 3000

