apiVersion: "v1"
kind: "Service"
metadata:
  name: "user-service"
  namespace: "default"
  labels:
    app: "user"
spec:
  ports:
  - protocol: "TCP"
    port: 3000
    targetPort: 3000
  selector:
    app: "user"
  type: "LoadBalancer"
